randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 208, in <module>
    wo.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 210, in <module>
    prc.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 208, in <module>
    wo.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 210, in <module>
    prc.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 210, in <module>
    prc.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 208, in <module>
    wo.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 208, in <module>
    wo.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 208, in <module>
    wo.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
Process Process-1:
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
usage: miner.py [-h] [--nicehash] [--host HOST] [--port PORT]
miner.py: error: unrecognized arguments: &
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 208, in <module>
    wo.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
Traceback (most recent call last):
  File "/workspaces/mminer/wminer/miner.py", line 210, in <module>
    prc.join()
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/local/python/3.10.4/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
randomx: Couldn't use largePages for RandomX cache
randomx: Couldn't use largePages for RandomX dataset
